# Site settings
title: Bibliographie de François Goffinet
tag_text: Bibliographie de François Goffinet
description: "Liste des supports numériques et des sites de formation par domaines IT (informatique)"
url: "https://biblio.goffinet.org/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

github_username: goffinet #test
twitter_username: goffinet #test
linkedin_username: fegoffinet #test
youtube_channel: #test
slideshare_username: fegoffinet #test
gitbook_username: #test
gitlab_username: goffinet

google_analytics: UA-79826195-1 #

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      read_time: true
      toc: true

# Build settings
markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
