# Site settings
title: "Bibliographie de François-Emmanuel Goffinet"
tag_text: "Bibliographie de François-Emmanuel Goffinet"
description: "Liste des supports numériques et des sites de formation par domaines IT (informatique), Bibliographie de François-Emmanuel Goffinet"
url: "https://biblio.goffinet.org/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

github_username: goffinet
twitter_username: goffinet
linkedin_username: fegoffinet
youtube_channel:
slideshare_username: fegoffinet
gitbook_username:
gitlab_username: goffinet
email: goffinet@goffinet.eu
web: "https://www.goffinet.org/"

google_analytics: UA-21733018-25

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      read_time: true
      toc: true

# Build settings
markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-extlinks

# https://github.com/d-ogarkov/jekyll-extlinks
extlinks:
  attributes: {rel: nofollow, target: _blank}
  rel_exclude: ['biblio.goffinet.org', '127.0.0.1', 'localhost']
